### ISSUE TITLE
Add toggle to "Auto-BTC"

### ISSUE THREAD

**Issue by LiamTownsley** [HEScriptsPack/BetterHExBot#1]
You should add a toggle for
```
Tranfers earned money to BTC wallet automatically
```
as they BTC wallet may be breached

**Comment by Logfro** [comment]
Explain further please,
an on and off checkbox is already there

**Comment by LiamTownsley** [comment]
Ah, I cannot see this- may be due to adblock due to a  previously blocked element but I will disable this and check if I can see it

**Comment by LiamTownsley** [comment]
My mistake, I have previously blocked that element before- issue fixed (please re-tag)
