### ISSUE TITLE
Updating the code

### ISSUE THREAD

**Issue by lishalzal** [HEScriptsPack/BetterHExBot#19]
Could you please update the code to work on: https://hackerwars.io/

**Comment by lishalzal** [comment]
please

**Comment by aurumhf** [comment]
I went in and added in the new link to the code. Still not operational. Looked through the code to see if anything obvious jumped out at me and it didnt. Even if dev could just tell us what to edit to get it working again.

thanks!

**Comment by Logfro** [comment]
Read last answer in https://github.com/HEScriptsPack/BetterHExBot/issues/18 i wont repeat myself
